### ISSUE TITLE
error CustomResourceDefinition

### ISSUE THREAD

**Issue by agungsaputro** [hokstack/hok-operator#2]
I'm using kubeadm with kubernetes version 1.22.2

and got error
`Error: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"`

**Comment by rohitrsh** [comment]
This helm chart is not updated for Kube version 1.22, to make it work you might want to update deprecated APIs and test.

**Comment by agungsaputro** [comment]
so what version of kube is this running on?
